import { getServerSideAuthProps } from "@/components/ProvidersAuth";
import MiddlewareAuth from "@/components/ProvidersAuth/MiddlewareAuth";
import ProviderAuth from "@/components/ProvidersAuth/ProviderAuth";
import type { Metadata } from "next";

import { Inter } from "next/font/google";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LayoutAunteticated({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSideAuthProps();

 

  return (
    <html lang="en">
      <ProviderAuth session={session!}>
        <MiddlewareAuth>
          <body className={inter.className}>{children}</body>
        </MiddlewareAuth>
      </ProviderAuth>
    </html>
  );
}
